version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout

      - restore_cache:
          keys:
            - wilco-api-{{ checksum "pom.xml" }}
            - wilco-api-

      - run: cd java; mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: wilco-api-{{ checksum "pom.xml" }}

      - run: mvn integration-test